version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
  nginx:
    image: nginx:1.19.3
    restart: unless-stopped    
    ports:
      - 80:80
    volumes:
      - ./nginx/web-api.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api